#!/bin/bash

MODEL_PV_PREFIX=test

source $PACKAGE_TOP/anaconda/envs/lume/bin/activate
export PYTHONPATH=$(pwd):$PYTHONPATH
source $EPICS_SETUP/envSet_prodOnDev.bash

serve-from-template files/model_config.yml ${MODEL_PV_PREFIX} &
python bridge.py --model_pv_prefix ${MODEL_PV_PREFIX} &