#!/bin/bash
source $PACKAGE_TOP/anaconda/envs/lume-demo/bin/activate
export PYTHONPATH=$(pwd):$PYTHONPATH
source $EPICS_SETUP/envSet_prodOnDev.bash
export EPICS_CA_ADDR_LIST="$EPICS_CA_ADDR_LIST 127.255.255.255"

MODEL_PV_PREFIX=test

python bridge.py --model_pv_prefix "${MODEL_PV_PREFIX}:"
